import Sidebar from "@/components/Sidebar";
import Providers from "@/redux/providers/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <div>
        <div>
          <Sidebar />
        </div>
        <div>{children}</div>
      </div>
    </Providers>
  );
}
